package com.odison.saleview.bean;

import java.math.BigDecimal;

public class Account extends AccountKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.balance
     *
     * @return the value of tbl_account.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.balance
     *
     * @param balance the value for tbl_account.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }


}