package com.odison.saleview.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MainOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.merchant_id
     *
     * @mbggenerated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.location_id
     *
     * @mbggenerated
     */
    private Integer locationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.courier_id
     *
     * @mbggenerated
     */
    private Integer courierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.reword
     *
     * @mbggenerated
     */
    private BigDecimal reword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.take_time
     *
     * @mbggenerated
     */
    private Date takeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.embrace_time
     *
     * @mbggenerated
     */
    private Date embraceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.finish_time
     *
     * @mbggenerated
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.embrace_code
     *
     * @mbggenerated
     */
    private String embraceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.county
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.sub_count
     *
     * @mbggenerated
     */
    private Integer subCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_mainorder.sub_finished_count
     *
     * @mbggenerated
     */
    private Integer subFinishedCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.id
     *
     * @return the value of tbl_mainorder.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.id
     *
     * @param id the value for tbl_mainorder.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.merchant_id
     *
     * @return the value of tbl_mainorder.merchant_id
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.merchant_id
     *
     * @param merchantId the value for tbl_mainorder.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.location_id
     *
     * @return the value of tbl_mainorder.location_id
     *
     * @mbggenerated
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.location_id
     *
     * @param locationId the value for tbl_mainorder.location_id
     *
     * @mbggenerated
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.courier_id
     *
     * @return the value of tbl_mainorder.courier_id
     *
     * @mbggenerated
     */
    public Integer getCourierId() {
        return courierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.courier_id
     *
     * @param courierId the value for tbl_mainorder.courier_id
     *
     * @mbggenerated
     */
    public void setCourierId(Integer courierId) {
        this.courierId = courierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.reword
     *
     * @return the value of tbl_mainorder.reword
     *
     * @mbggenerated
     */
    public BigDecimal getReword() {
        return reword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.reword
     *
     * @param reword the value for tbl_mainorder.reword
     *
     * @mbggenerated
     */
    public void setReword(BigDecimal reword) {
        this.reword = reword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.state
     *
     * @return the value of tbl_mainorder.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.state
     *
     * @param state the value for tbl_mainorder.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.create_time
     *
     * @return the value of tbl_mainorder.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.create_time
     *
     * @param createTime the value for tbl_mainorder.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.take_time
     *
     * @return the value of tbl_mainorder.take_time
     *
     * @mbggenerated
     */
    public Date getTakeTime() {
        return takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.take_time
     *
     * @param takeTime the value for tbl_mainorder.take_time
     *
     * @mbggenerated
     */
    public void setTakeTime(Date takeTime) {
        this.takeTime = takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.embrace_time
     *
     * @return the value of tbl_mainorder.embrace_time
     *
     * @mbggenerated
     */
    public Date getEmbraceTime() {
        return embraceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.embrace_time
     *
     * @param embraceTime the value for tbl_mainorder.embrace_time
     *
     * @mbggenerated
     */
    public void setEmbraceTime(Date embraceTime) {
        this.embraceTime = embraceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.finish_time
     *
     * @return the value of tbl_mainorder.finish_time
     *
     * @mbggenerated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.finish_time
     *
     * @param finishTime the value for tbl_mainorder.finish_time
     *
     * @mbggenerated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.embrace_code
     *
     * @return the value of tbl_mainorder.embrace_code
     *
     * @mbggenerated
     */
    public String getEmbraceCode() {
        return embraceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.embrace_code
     *
     * @param embraceCode the value for tbl_mainorder.embrace_code
     *
     * @mbggenerated
     */
    public void setEmbraceCode(String embraceCode) {
        this.embraceCode = embraceCode == null ? null : embraceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.address
     *
     * @return the value of tbl_mainorder.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.address
     *
     * @param address the value for tbl_mainorder.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.province
     *
     * @return the value of tbl_mainorder.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.province
     *
     * @param province the value for tbl_mainorder.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.city
     *
     * @return the value of tbl_mainorder.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.city
     *
     * @param city the value for tbl_mainorder.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.county
     *
     * @return the value of tbl_mainorder.county
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.county
     *
     * @param county the value for tbl_mainorder.county
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.sub_count
     *
     * @return the value of tbl_mainorder.sub_count
     *
     * @mbggenerated
     */
    public Integer getSubCount() {
        return subCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.sub_count
     *
     * @param subCount the value for tbl_mainorder.sub_count
     *
     * @mbggenerated
     */
    public void setSubCount(Integer subCount) {
        this.subCount = subCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_mainorder.sub_finished_count
     *
     * @return the value of tbl_mainorder.sub_finished_count
     *
     * @mbggenerated
     */
    public Integer getSubFinishedCount() {
        return subFinishedCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_mainorder.sub_finished_count
     *
     * @param subFinishedCount the value for tbl_mainorder.sub_finished_count
     *
     * @mbggenerated
     */
    public void setSubFinishedCount(Integer subFinishedCount) {
        this.subFinishedCount = subFinishedCount;
    }
}