package com.odison.saleview.bean;


import java.io.Serializable;

public class MerchantLocation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_merchant_locations.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_merchant_locations.merchant_id
     *
     * @mbggenerated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_merchant_locations.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_merchant_locations.lng
     *
     * @mbggenerated
     */
    private Double lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_merchant_locations.lat
     *
     * @mbggenerated
     */
    private Double lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_merchant_locations.id
     *
     * @return the value of tbl_merchant_locations.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_merchant_locations.id
     *
     * @param id the value for tbl_merchant_locations.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_merchant_locations.merchant_id
     *
     * @return the value of tbl_merchant_locations.merchant_id
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_merchant_locations.merchant_id
     *
     * @param merchantId the value for tbl_merchant_locations.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_merchant_locations.location
     *
     * @return the value of tbl_merchant_locations.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_merchant_locations.location
     *
     * @param location the value for tbl_merchant_locations.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_merchant_locations.lng
     *
     * @return the value of tbl_merchant_locations.lng
     *
     * @mbggenerated
     */
    public Double getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_merchant_locations.lng
     *
     * @param lng the value for tbl_merchant_locations.lng
     *
     * @mbggenerated
     */
    public void setLng(Double lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_merchant_locations.lat
     *
     * @return the value of tbl_merchant_locations.lat
     *
     * @mbggenerated
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_merchant_locations.lat
     *
     * @param lat the value for tbl_merchant_locations.lat
     *
     * @mbggenerated
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }
}