package com.odison.saleview.bean;

import java.util.Date;

public class SubOrder  {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.main_order_id
     *
     * @mbggenerated
     */
    private Integer mainOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.merchant_id
     *
     * @mbggenerated
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.merchant_location_id
     *
     * @mbggenerated
     */
    private Integer merchantLocationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.merchant_order_id
     *
     * @mbggenerated
     */
    private String merchantOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.commodity_id
     *
     * @mbggenerated
     */
    private Integer commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.sub_index
     *
     * @mbggenerated
     */
    private Integer subIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.pack_time
     *
     * @mbggenerated
     */
    private Date packTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.take_time
     *
     * @mbggenerated
     */
    private Date takeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.embrace_time
     *
     * @mbggenerated
     */
    private Date embraceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.arrived_time
     *
     * @mbggenerated
     */
    private Date arrivedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.receiver_name
     *
     * @mbggenerated
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.receiver_phone
     *
     * @mbggenerated
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.receiver_address
     *
     * @mbggenerated
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.receiver_lng
     *
     * @mbggenerated
     */
    private Double receiverLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_suborder.receiver_lat
     *
     * @mbggenerated
     */
    private Double receiverLat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.id
     *
     * @return the value of tbl_suborder.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.id
     *
     * @param id the value for tbl_suborder.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.main_order_id
     *
     * @return the value of tbl_suborder.main_order_id
     *
     * @mbggenerated
     */
    public Integer getMainOrderId() {
        return mainOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.main_order_id
     *
     * @param mainOrderId the value for tbl_suborder.main_order_id
     *
     * @mbggenerated
     */
    public void setMainOrderId(Integer mainOrderId) {
        this.mainOrderId = mainOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.merchant_id
     *
     * @return the value of tbl_suborder.merchant_id
     *
     * @mbggenerated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.merchant_id
     *
     * @param merchantId the value for tbl_suborder.merchant_id
     *
     * @mbggenerated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.merchant_location_id
     *
     * @return the value of tbl_suborder.merchant_location_id
     *
     * @mbggenerated
     */
    public Integer getMerchantLocationId() {
        return merchantLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.merchant_location_id
     *
     * @param merchantLocationId the value for tbl_suborder.merchant_location_id
     *
     * @mbggenerated
     */
    public void setMerchantLocationId(Integer merchantLocationId) {
        this.merchantLocationId = merchantLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.merchant_order_id
     *
     * @return the value of tbl_suborder.merchant_order_id
     *
     * @mbggenerated
     */
    public String getMerchantOrderId() {
        return merchantOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.merchant_order_id
     *
     * @param merchantOrderId the value for tbl_suborder.merchant_order_id
     *
     * @mbggenerated
     */
    public void setMerchantOrderId(String merchantOrderId) {
        this.merchantOrderId = merchantOrderId == null ? null : merchantOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.state
     *
     * @return the value of tbl_suborder.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.state
     *
     * @param state the value for tbl_suborder.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.commodity_id
     *
     * @return the value of tbl_suborder.commodity_id
     *
     * @mbggenerated
     */
    public Integer getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.commodity_id
     *
     * @param commodityId the value for tbl_suborder.commodity_id
     *
     * @mbggenerated
     */
    public void setCommodityId(Integer commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.sub_index
     *
     * @return the value of tbl_suborder.sub_index
     *
     * @mbggenerated
     */
    public Integer getSubIndex() {
        return subIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.sub_index
     *
     * @param subIndex the value for tbl_suborder.sub_index
     *
     * @mbggenerated
     */
    public void setSubIndex(Integer subIndex) {
        this.subIndex = subIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.create_time
     *
     * @return the value of tbl_suborder.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.create_time
     *
     * @param createTime the value for tbl_suborder.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.pack_time
     *
     * @return the value of tbl_suborder.pack_time
     *
     * @mbggenerated
     */
    public Date getPackTime() {
        return packTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.pack_time
     *
     * @param packTime the value for tbl_suborder.pack_time
     *
     * @mbggenerated
     */
    public void setPackTime(Date packTime) {
        this.packTime = packTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.take_time
     *
     * @return the value of tbl_suborder.take_time
     *
     * @mbggenerated
     */
    public Date getTakeTime() {
        return takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.take_time
     *
     * @param takeTime the value for tbl_suborder.take_time
     *
     * @mbggenerated
     */
    public void setTakeTime(Date takeTime) {
        this.takeTime = takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.embrace_time
     *
     * @return the value of tbl_suborder.embrace_time
     *
     * @mbggenerated
     */
    public Date getEmbraceTime() {
        return embraceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.embrace_time
     *
     * @param embraceTime the value for tbl_suborder.embrace_time
     *
     * @mbggenerated
     */
    public void setEmbraceTime(Date embraceTime) {
        this.embraceTime = embraceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.arrived_time
     *
     * @return the value of tbl_suborder.arrived_time
     *
     * @mbggenerated
     */
    public Date getArrivedTime() {
        return arrivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.arrived_time
     *
     * @param arrivedTime the value for tbl_suborder.arrived_time
     *
     * @mbggenerated
     */
    public void setArrivedTime(Date arrivedTime) {
        this.arrivedTime = arrivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.receiver_name
     *
     * @return the value of tbl_suborder.receiver_name
     *
     * @mbggenerated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.receiver_name
     *
     * @param receiverName the value for tbl_suborder.receiver_name
     *
     * @mbggenerated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.receiver_phone
     *
     * @return the value of tbl_suborder.receiver_phone
     *
     * @mbggenerated
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.receiver_phone
     *
     * @param receiverPhone the value for tbl_suborder.receiver_phone
     *
     * @mbggenerated
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.receiver_address
     *
     * @return the value of tbl_suborder.receiver_address
     *
     * @mbggenerated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.receiver_address
     *
     * @param receiverAddress the value for tbl_suborder.receiver_address
     *
     * @mbggenerated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.receiver_lng
     *
     * @return the value of tbl_suborder.receiver_lng
     *
     * @mbggenerated
     */
    public Double getReceiverLng() {
        return receiverLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.receiver_lng
     *
     * @param receiverLng the value for tbl_suborder.receiver_lng
     *
     * @mbggenerated
     */
    public void setReceiverLng(Double receiverLng) {
        this.receiverLng = receiverLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_suborder.receiver_lat
     *
     * @return the value of tbl_suborder.receiver_lat
     *
     * @mbggenerated
     */
    public Double getReceiverLat() {
        return receiverLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_suborder.receiver_lat
     *
     * @param receiverLat the value for tbl_suborder.receiver_lat
     *
     * @mbggenerated
     */
    public void setReceiverLat(Double receiverLat) {
        this.receiverLat = receiverLat;
    }
}